### PR TITLE
ENH: PatchBasedDenoisingImageFilter outputs 'double' pixel type images

### PR DESCRIPTION
**Pull request by fbudin69500**
Updating BasicFilters_PatchBasedDenoisingImageFilter_default.nrrd as
PatchBasedDenoisingImageFilter now outputs 'double' pixel type images.
New image was generated using only one thread.
  export ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS=1
Input image pixel type was converted to double.
New baseline image was generated using this new input image and
  SimpleITK Python.PatchBasedDenoisingImageFilter.default test
  modified command line to use this converted input.

### CODE REVIEW

**Comment by fbudin69500** [comment]
@imikejackson Please review

**Comment by fbudin69500** [comment]
@imikejackson  Just a reminder in case you haven't seen this.

**Comment by imikejackson** [comment]
Looks good. merge when you can.

**Comment by fbudin69500** [comment]
@imikejackson I don't have the rights on this repository.

**Pull request merged**
